export const FETCH_PRODUCTS_HOME = 'FETCH_PRODUCTS_HOME';
export const FECTCH_MENU = "FECTCH_MENU";
export const FETCH_PRODUCTS_CATALOG = "FETCH_PRODUCTS_CATALOG";
export const FETCH_PRODUCTS_CATALOG_CHILD = "FETCH_PRODUCTS_CATALOG_CHILD";
export const FETCH_PRODUCT_DETAILT = "FETCH_PRODUCT_DETAILT";

export const OAUTH_ERROR = "OAUTH_ERROR";
export const OAUTH_SIGN_UP = "OAUTH_SIGN_UP"

export const OAUTH_SIGN_IN = "OAUTH_SIGN_IN"
export const OAUTH_GOOGLE = "OAUTH_GOOGLE"
export const OAUTH_FACEBOOK = "OAUTH_FACEBOOK"
export const LOGOUT_USER = "LOGOUT_USER"
export const OAUTH_GET_USER = "OAUTH_GET_USER"