export const FETCH_PRODUCTS_HOME = 'FETCH_PRODUCTS_HOME';
export const FECTCH_MENU = "FECTCH_MENU";

export const FETCH_PRODUCTS_CATALOG = "FETCH_PRODUCTS_CATALOG";
export const FETCH_PRODUCTS_CATALOG_CHILD = "FETCH_PRODUCTS_CATALOG_CHILD";
export const FETCH_PRODUCT_DETAILT = "FETCH_PRODUCT_DETAILT";
export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const RESET_PATH ='RESET_PATH'

export const OAUTH_ERROR = "OAUTH_ERROR";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const OAUTH_SIGN_UP = "OAUTH_SIGN_UP"

export const OAUTH_SIGN_IN = "OAUTH_SIGN_IN"
export const OAUTH_GOOGLE = "OAUTH_GOOGLE"
export const OAUTH_FACEBOOK = "OAUTH_FACEBOOK"
export const LOGOUT_USER = "LOGOUT_USER"
export const OAUTH_GET_USER = "OAUTH_GET_USER"
export const RESET_MESSAGE = "RESET_MESSAGE"
export const RESET_ERROR_SIGNIN = "RESET_ERROR_SIGNIN"

export const COUNT_USER_ONLINE = 'COUNT_USER_ONLINE'

export const ADD_TO_CART = "ADD_TO_CART";
export const FECTCH_GET_CART = "FECTCH_GET_CART";
export const DELETE_CART = "DELETE_CART";
export const UPDATE_CART = "UPDATE_CART"

export const ADD_TO_CART_LOCAL = "ADD_TO_CART_LOCAL"
export const DELETE_CART_LOCAL = 'DELETE_CART_LOCAL'
export const UPDATE_CART_LOCAL = 'UPDATE_CART_LOCAL'

export const GET_DISTRICTS = 'GET_DISTRICTS'
export const GET_WARDS = 'GET_WARDS'
export const GET_SERVICES = 'GET_SERVICES'
export const CHECKOUT_ORDER = 'CHECKOUT_ORDER';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const STORE_INFO = 'STORE_INFO'
export const RESTORE_INFO = 'RESTORE_INFO'

export const SEARCH_KEY ='SEARCH_KEY';
export const FILTER_SEARCH_PRODUCT = 'FILTER_SEARCH_PRODUCT';

export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY'

export const GET_POST = 'GET_POST'
export const GET_POST_DETAILT = 'GET_POST_DETAILT'